---
fixtures:
  forge_modules:
    stdlib: 'puppetlabs/stdlib'
    concat: 'puppetlabs/concat'
    augeas_core: 'puppetlabs/augeas_core'
    chocolatey: 'puppetlabs/chocolatey'
    host_core: 'puppetlabs/host_core'
    sshkeys_core: 'puppetlabs/sshkeys_core'
    zfs_core: 'puppetlabs/zfs_core'
    dnsquery: 'puppet/dnsquery'
    augeasproviders_core: 'puppet/augeasproviders_core'
    augeasproviders_sysctl: 'puppet/augeasproviders_sysctl'
    mysql: 'puppetlabs/mysql'
    powershell: 'puppetlabs/powershell'
    nodejs: 'puppet/nodejs'
    windows_env: 'puppet/windows_env'
    windows_firewall: 'puppet/windows_firewall'
    puppet: 'theforeman/puppet'
    extlib: 'puppet/extlib'
    systemd: 'puppet/systemd'
    registry: 'puppetlabs/registry'
  repositories:
    vcsrepo: 'https://gitlab.james.tl/nest/forks/puppet-vcsrepo.git'
    firewalld:
      repo: 'https://gitlab.james.tl/nest/forks/puppet-firewalld.git'
      branch: 'fix-new-zone-creation'
    portage: 'https://gitlab.james.tl/nest/forks/puppet-portage.git'
