---
default:
  interruptible: true

stages:
  - 'Test'
  - 'Build'
  - 'Deploy'

'Validate':
  image: '${CI_REGISTRY}/nest/tools/pdk'
  stage: 'Test'
  script:
    - 'pdk validate'

'Unit Test':
  image: '${CI_REGISTRY}/nest/tools/pdk'
  stage: 'Test'
  script:
    - 'pdk test unit --parallel --verbose'

.template: &template
  image: '${CI_REGISTRY}/nest/tools/bolt'
  stage: 'Build'
  script:
    - 'chmod o-w .' # Bolt security requirement
    - 'bin/build config "$CPU"
        branch="$CI_COMMIT_BRANCH"
        deploy=true
        git_private_key_var=NEST_CI_DEPLOY_KEY
        git_repository="$CI_REPOSITORY_URL"
        registry="$CI_REGISTRY"
        registry_username="$CI_REGISTRY_USER"
        registry_password_var=CI_REGISTRY_PASSWORD'
  rules:
    - if: '$BUILD == $CPU'
    - if: '$BUILD'
      when: never
    - when: always

'Build haswell':
  <<: *template
  tags: ['amd64']
  variables:
    CPU: 'haswell'

'Build cortex-a53':
  <<: *template
  tags: ['arm64']
  variables:
    CPU: 'cortex-a53'

'Build rv64gc':
  <<: *template
  tags: ['riscv64']
  variables:
    CPU: 'rv64gc'

'Deploy environment':
  stage: 'Deploy'
  tags: ['r10k']
  script:
    - 'r10k deploy environment "$CI_COMMIT_BRANCH" -pv'

'Deploy image':
  stage: 'Deploy'
  image: '${CI_REGISTRY}/nest/tools/bolt'
  variables:
    CPUS: '["haswell", "cortex-a53", "rv64gc"]' # json array
  script:
    - 'chmod o-w .' # Bolt security requirement
    - 'bolt plan run nest::build::manifest
        image="${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}"
        image_tags="$CPUS"
        deploy=true
        registry="$CI_REGISTRY"
        registry_username="$CI_REGISTRY_USER"
        registry_password_var=CI_REGISTRY_PASSWORD'