---
default:
  interruptible: true

stages:
  - 'Deploy'
  - 'Test'
  - 'Build'

'Validate':
  image: '${CI_REGISTRY}/nest/tools/pdk:${CI_HOST_CPU}'
  stage: 'Test'
  script:
    - 'pdk validate'

'Unit Test':
  image: '${CI_REGISTRY}/nest/tools/pdk:${CI_HOST_CPU}'
  stage: 'Test'
  script:
    - 'pdk test unit --parallel --verbose'

.template: &template
  stage: 'Build'
  script:
    - 'echo "$CI_REGISTRY_PASSWORD" | podman login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"'
    - 'mkdir empty'
    - 'podman build
        --build-arg BOLT_TAG="$CPU"
        --build-arg SSH_PRIVATE_KEY="$(< "$SSH_PRIVATE_KEY")"
        -f Containerfile
        -t "${CI_REGISTRY_IMAGE}:${CPU}" empty'
    - 'podman push "${CI_REGISTRY_IMAGE}:${CPU}"'
  rules:
    - if: '$BUILD == $CPU'
    - if: '$BUILD'
      when: never
    - when: always

'Build haswell':
  <<: *template
  tags: ['amd64']
  variables:
    CPU: 'haswell'

'Build cortex-a53':
  <<: *template
  tags: ['arm64']
  variables:
    CPU: 'cortex-a53'

'Build rv64gc':
  <<: *template
  tags: ['riscv64']
  variables:
    CPU: 'rv64gc'

'Deploy':
  stage: 'Deploy'
  tags: ['r10k']
  script:
    - 'r10k deploy environment "$CI_COMMIT_BRANCH" -pv'
