---
default:
  interruptible: true

stages:
  - 'Test'
  - 'Deploy'

'Validate':
  image: '${CI_REGISTRY}/nest/tools/pdk'
  stage: 'Test'
  script:
    - 'pdk validate'

'Unit Test':
  image: '${CI_REGISTRY}/nest/tools/pdk'
  stage: 'Test'
  script:
    - 'pdk test unit --parallel --verbose'

'Deploy environment':
  stage: 'Deploy'
  tags: ['r10k']
  script:
    - 'r10k deploy environment "$CI_COMMIT_BRANCH" -pv'

'Deploy image':
  stage: 'Deploy'
  variables:
    SSH_PRIVATE_KEY: '$NEST_CI_DEPLOY_KEY'
  script:
    - 'echo "$CI_REGISTRY_PASSWORD" | podman login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"'
    - 'mkdir empty'
    - 'podman build
        --build-arg=BRANCH="$CI_COMMIT_BRANCH"
        --build-arg=REPOSITORY="$CI_REPOSITORY_URL"
        --build-arg=SSH_PRIVATE_KEY
        --file=Containerfile
        --jobs=$(nproc)
        --manifest="${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}"
        --platform=linux/amd64,linux/arm64,linux/riscv64
        --volume=/usr/bin/qemu-aarch64:/usr/bin/qemu-aarch64:ro
        --volume=/usr/bin/qemu-riscv64:/usr/bin/qemu-riscv64:ro
        --squash
        empty'
    - 'podman manifest push --all "${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}"'
