---
default:
  interruptible: true

stages:
  - 'Test'
  - 'Build'
  - 'Deploy'

'Validate':
  image: '${CI_REGISTRY}/nest/tools/pdk:${CI_HOST_CPU}'
  stage: 'Test'
  script:
    - 'pdk validate --puppet-version=8.4.0'

'Unit Test':
  image: '${CI_REGISTRY}/nest/tools/pdk:${CI_HOST_CPU}'
  stage: 'Test'
  script:
    - 'pdk test unit --puppet-version=8.4.0 --verbose'

.template: &template
  image: '${CI_REGISTRY}/nest/tools/buildah:${CI_HOST_CPU}'
  stage: 'Build'
  script:
    - 'eval $(ssh-agent -s)'
    - 'chmod 600 "$SSH_PRIVATE_KEY"'
    - 'ssh-add "$SSH_PRIVATE_KEY"'
    - '[[ $CPU == cortex-* ]] && QEMU_ARCH=aarch64'
    - '[[ -f "/usr/bin/qemu-${QEMU_ARCH}" ]] && qemu_args="-v /usr/bin/qemu-${QEMU_ARCH}:/usr/bin/qemu-${QEMU_ARCH}:ro"'
    - 'buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"'
    - 'buildah bud --build-arg BOLT_TAG="$CPU"
                   --build-arg SSH_AUTH_SOCK="$SSH_AUTH_SOCK"
                   -v "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}:ro"
                   $qemu_args
                   -t "${CI_REGISTRY_IMAGE}:${CPU}" .'
    - 'buildah push "${CI_REGISTRY_IMAGE}:${CPU}"'
  rules:
    - if: '$BUILD && $BUILD != $CPU'
      when: never
    - when: always

'Build haswell':
  <<: *template
  tags: ['amd64']
  variables:
    CPU: 'haswell'

'Build cortex-a53':
  <<: *template
  tags: ['arm64']
  variables:
    CPU: 'cortex-a53'

'Deploy':
  stage: 'Deploy'
  tags: ['r10k']
  script:
    - 'r10k deploy environment "$CI_COMMIT_BRANCH" -pv'
