---
stages:
  - test
  - deploy

validate:
  image: '${CI_REGISTRY}/nest/tools/pdk:${CI_HOST_CPU}'
  stage: 'test'
  script:
    - 'pdk validate --puppet-version=8.2.0'

r10k:
  stage: 'deploy'
  tags: ['r10k']
  script:
    - 'r10k deploy environment "$CI_COMMIT_BRANCH" -pv'
