---
default:
  interruptible: true

stages:
  - 'Test'
  - 'Build'
  - 'Deploy'

'Validate':
  image: '${CI_REGISTRY}/nest/tools/pdk'
  stage: 'Test'
  script:
    - 'pdk validate'

'Unit Test':
  image: '${CI_REGISTRY}/nest/tools/pdk'
  stage: 'Test'
  script:
    - 'pdk test unit --parallel --verbose'

.template:
  stage: 'Build'
  variables:
    SSH_PRIVATE_KEY: "$NEST_CI_DEPLOY_KEY"
  script:
    - 'mkdir empty'
    - 'podman login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY" <<< $CI_REGISTRY_PASSWORD'
    - 'podman build
        --build-arg=BRANCH="$CI_COMMIT_BRANCH"
        --build-arg=REPOSITORY="$CI_REPOSITORY_URL"
        --build-arg=SSH_PRIVATE_KEY
        --file=Containerfile
        --squash
        --tag="${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}:${CPU}"
        empty'
    - 'podman push "${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}:${CPU}"'
  rules:
    - if: '$BUILD == $CPU'
    - if: '$BUILD'
      when: never
    - when: always

'Build haswell':
  extends: .template
  tags: ['amd64']
  variables:
    CPU: 'haswell'

'Build cortex-a53':
  extends: .template
  tags: ['arm64']
  variables:
    CPU: 'cortex-a53'

'Build rv64gc':
  extends: .template
  tags: ['riscv64']
  variables:
    CPU: 'rv64gc'

'Deploy environment':
  stage: 'Deploy'
  tags: ['r10k']
  script:
    - 'r10k deploy environment "$CI_COMMIT_BRANCH" -pv'

'Deploy image':
  stage: 'Deploy'
  variables:
    IMAGE: "${CI_PROJECT_PATH}/${CI_COMMIT_BRANCH}"
  script:
    - 'podman login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY" <<< $CI_REGISTRY_PASSWORD'
    - 'podman manifest exists "$IMAGE" && podman manifest rm "$IMAGE"'
    - 'podman manifest create "$IMAGE"'
    - 'podman manifest add "$IMAGE" "${CI_REGISTRY}/${IMAGE}:haswell"'
    - 'podman manifest add "$IMAGE" "${CI_REGISTRY}/${IMAGE}:cortex-a53"'
    - 'podman manifest add "$IMAGE" "${CI_REGISTRY}/${IMAGE}:rv64gc"'
    - 'podman manifest push --all "$IMAGE" "${CI_REGISTRY}/${IMAGE}"'
