---
.gitignore:
  paths:
    - '!/inventory.yaml'
    - '/bolt-debug.log'
    - '/.rerun.json'
    - 'private'

.gitlab-ci.yml:
  custom:
    custom_stages:
      - 'deploy'
    custom_jobs:
      r10k:
        stage: 'deploy'
        tags: ['r10k']
        script: 'r10k deploy environment -pv "$CI_COMMIT_BRANCH"'

.rubocop.yml:
  default_configs:
    AllCops:
      Exclude:
        - 'lib/puppet/provider/package/cygwin.rb'

Rakefile:
  # I have my own style and that is OK
  extra_disabled_lint_checks:
    - 2sp_soft_tabs
    - arrow_on_right_operand_line
    - autoloader_layout
    - case_without_default
    - documentation
    - nested_classes_or_defines
    - variable_scope
