---
.gitignore:
  paths:
    - '!/inventory.yaml'
    - '/bolt-debug.log'
    - '/.rerun.json'
    - 'private'

.rubocop.yml:
  default_configs:
    AllCops:
      Exclude:
        - 'lib/puppet/provider/package/cygwin.rb'

Rakefile:
  extra_disabled_lint_checks:
    - arrow_on_right_operand_line
    - case_without_default
    - documentation
