---
.gitignore:
  paths:
    - '!/bin/'
    - '/bin/*'
    - '!/bin/build'
    - '!/bin/bolt-wrapper'
    - '!/inventory.yaml'
    - '/bolt-debug.log'
    - '/build'
    - '/.modules'
    - '/.plan_cache.json'
    - '/.rerun.json'
    - '/.resource_types'
    - '/.task_cache.json'

.rubocop.yml:
  default_configs:
    AllCops:
      Exclude:
        - 'lib/puppet/provider/package/cygwin.rb'

Rakefile:
  # I have my own style and that is OK
  extra_disabled_lint_checks:
    - arrow_on_right_operand_line
    - autoloader_layout
    - case_without_default
    - documentation
    - manifest_whitespace_closing_bracket_after
    - manifest_whitespace_opening_brace_before
    - manifest_whitespace_two_empty_lines
    - nested_classes_or_defines
    - parameter_documentation
    - strict_indent
    - variable_scope

spec/default_facts.yml:
  extra_facts:
    processors:
      count: 8
    memory:
      system:
        total_bytes: 16484859904
    mountpoints:
      /boot: {}
    networking:
      fqdn: 'test.example.com'
    path: '/usr/local/bin:/usr/bin:/bin'
    portage_cflags: '-mcpu=cortex-a72 -O2 -pipe -ggdb'
    portage_use: 'X a52 aac acl acpi activities alsa arm64 bluetooth branding bzip2 cairo cdda cdr cli crypt cups dbus declarative dri dts dvdr encode exif flac fortran gdbm gif gpm gtk gui iconv icu ipv6 jpeg kde kwallet lcms libnotify libtirpc mad mng mp3 mp4 mpeg ncurses networkmanager nls nptl ogg opengl openmp pam pango pcre pdf pipewire plasma png policykit ppds pulseaudio qml qt5 readline screencast sdl seccomp semantic-desktop sound spell ssl startup-notification svg systemd test-rust tiff truetype udev udisks unicode upower usb vorbis vulkan wayland widgets wxwidgets x264 xattr xcb xft xml xv xvid zlib zsh-completion'

spec/spec_helper.rb:
  hiera_config_ruby: "File.expand_path(File.join(__FILE__, '../fixtures/hiera.yaml'))"
