---
.gitignore:
  paths:
    - '!/inventory.yaml'
    - '/bolt-debug.log'
    - '/.modules'
    - '/.plan_cache.json'
    - '/.rerun.json'
    - '/.resource_types'
    - '/.task_cache.json'

.rubocop.yml:
  default_configs:
    AllCops:
      Exclude:
        - 'lib/puppet/provider/package/cygwin.rb'

Rakefile:
  # I have my own style and that is OK
  extra_disabled_lint_checks:
    - arrow_on_right_operand_line
    - autoloader_layout
    - case_without_default
    - documentation
    - manifest_whitespace_closing_bracket_after
    - manifest_whitespace_opening_brace_before
    - manifest_whitespace_two_empty_lines
    - nested_classes_or_defines
    - parameter_documentation
    - strict_indent
    - variable_scope
