---
.gitignore:
  paths:
    - '!/inventory.yaml'
    - '/bolt-debug.log'
    - '/.rerun.json'
    - 'private'

.gitlab-ci.yml:
  override: true
  custom:
    bundler_args: '--without system_tests --path vendor/bundle --jobs $(nproc)'
    cache:
      paths:
        - 'vendor/bundle'
    custom_stages:
      - 'syntax'
      - 'unit'
      - 'deploy'
    custom_jobs:
      r10k:
        stage: 'deploy'
        tags: ['r10k']
        script: 'r10k deploy environment -pv "$CI_COMMIT_BRANCH"'
    ruby_versions:
      2.7.2:
        checks:
          - 'validate lint rubocop' # same as default minus 'check'
          - 'parallel_spec'
        puppet_version: '~> 7'

.rubocop.yml:
  default_configs:
    AllCops:
      Exclude:
        - 'lib/puppet/provider/package/cygwin.rb'

Rakefile:
  # I have my own style and that is OK
  extra_disabled_lint_checks:
    - 2sp_soft_tabs
    - arrow_on_right_operand_line
    - autoloader_layout
    - case_without_default
    - documentation
    - nested_classes_or_defines
    - variable_scope
