---
.gitignore:
  paths:
    - '!/inventory.yaml'
    - '/bolt-debug.log'
    - '/.rerun.json'
    - 'private'

.rubocop.yml:
  default_configs:
    AllCops:
      Exclude:
        - 'lib/puppet/provider/package/cygwin.rb'
