---
description: 'Apply Kubernetes manifest'

parameters:
  targets:
    type: TargetSpec
    description: 'Host on which to run kubectl'
  manifest:
    type: String
    description: 'Path or URL to the Kubernets manifest to deploy'

steps:
  - description: "Apply Kubernetes manifest ${manifest}"
    command: "kubectl apply -f ${manifest}"
    env_vars:
      KUBECONFIG: /etc/kubernetes/admin.conf
    run_as: root
    targets: $targets
