---
description: 'Apply Kubernetes manifest'

parameters:
  manifest:
    type: String
    description: 'Path or URL to the Kubernets manifest to deploy'

steps:
  - description: "Apply Kubernetes manifest ${manifest}"
    command: "kubectl apply -f ${manifest}"
    targets: localhost
