---
description: 'Configure Kubernetes network'

steps:
  - description: 'Install kube-vip Cloud Provider'
    plan: 'nest::kubernetes::apply'
    parameters:
      manifest: 'nest/kubernetes/manifests/kube-vip-cloud-controller.yaml'

  - description: 'Configure kube-vip Cloud Provider'
    command: 'kubectl create configmap -n kube-system kubevip --from-literal cidr-global=172.21.0.0/17'
    targets: localhost
