---
description: 'Configure Kubernetes network'

steps:
  - description: 'Install MetalLB'
    plan: 'nest::kubernetes::helm_deploy'
    parameters:
      release: 'metallb'
      chart: 'metallb'
      namespace: 'metallb-system'
      repo_name: 'metallb'
      repo_url: 'https://metallb.github.io/metallb'
      version: '0.13.12'

  - description: 'Wait for MetalLB controller'
    plan: 'nest::kubernetes::wait'
    parameters:
      kind: deployment
      name: 'metallb-controller'
      namespace: 'metallb-system'

  - description: 'Configure MetalLB'
    plan: 'nest::kubernetes::apply'
    parameters:
      manifest: 'nest/kubernetes/manifests/metallb-config.yaml'

