---
description: 'Configure storage'

steps:
  - description: 'Install NFS CSI driver'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'csi-driver-nfs'
      app: 'csi-driver-nfs'
      namespace: 'kube-system'
      repo_name: 'csi-driver-nfs'
      repo_url: 'https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts'
      version: '4.9.0'
