---
description: 'Configure Kubernetes Calico network'

steps:
  - description: 'Wait for calico-apiserver deployment'
    plan: 'nest::kubernetes::wait'
    parameters:
      kind: deployment
      name: 'calico-apiserver'
      namespace: 'calico-apiserver'

  - description: 'Deploy calicoctl'
    plan: 'nest::kubernetes::apply'
    parameters:
      manifest: 'nest/kubernetes/manifests/calicoctl.yaml'

  - description: 'Wait for calicoctl pod'
    plan: 'nest::kubernetes::wait'
    parameters:
      kind: pod
      name: 'calicoctl'
      namespace: 'kube-system'

  - description: 'Configure Calico BGP'
    plan: 'nest::kubernetes::calicoctl_apply'
    parameters:
      manifest: 'nest/kubernetes/manifests/calico-config.yaml'

  - description: 'Install MetalLB'
    plan: 'nest::kubernetes::helm_install'
    parameters:
      name: 'metallb'
      chart: 'metallb'
      namespace: 'metallb-system'
      repo_name: 'metallb'
      repo_url: 'https://metallb.github.io/metallb'
      version: '0.13.12'

  - description: 'Wait for MetalLB controller'
    plan: 'nest::kubernetes::wait'
    parameters:
      kind: deployment
      name: 'metallb-controller'
      namespace: 'metallb-system'

  - description: 'Configure MetalLB address pool'
    plan: 'nest::kubernetes::apply'
    parameters:
      manifest: 'nest/kubernetes/manifests/metallb-config.yaml'
