---
description: 'Configure Kubernetes network'

parameters:
  calico:
    description: 'Deploy Calico'
    type: Boolean
    default: true

  metallb:
    description: 'Deploy MetalLB'
    type: Boolean
    default: true

steps:
  - description: 'Install Calico'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'calico'
      app: 'tigera-operator'
      namespace: 'tigera-operator'
      repo_name: 'projectcalico'
      repo_url: 'https://docs.tigera.io/calico/charts'
      version: '3.29.0'
      wait: true
      deploy: $calico

  - description: 'Configure Calico'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'calico-config'
      app: 'scratch'
      namespace: 'tigera-operator'
      chart: './files/kubernetes/chart'
      deploy: $calico

  - description: 'Install MetalLB'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'metallb'
      app: 'metallb'
      namespace: 'metallb-system'
      repo_name: 'metallb'
      repo_url: 'https://metallb.github.io/metallb'
      version: '0.14.8'
      wait: true
      deploy: $metallb

  - description: 'Configure MetalLB'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'metallb-config'
      app: 'scratch'
      namespace: 'metallb-system'
      chart: './files/kubernetes/chart'
      deploy: $metallb
