---
description: 'Create Kubernetes resources from a manifest'

parameters:
  manifest:
    type: String
    description: 'Path or URL to the Kubernets manifest to deploy'

steps:
  - description: "Create Kubernetes resources from ${manifest}"
    command: "kubectl create -f ${manifest}"
    targets: localhost
