---
description: 'Configure Ceph'

parameters:
  rook:
    description: 'Deploy Rook'
    type: Boolean
    default: true

  ceph:
    description: 'Deploy Ceph'
    type: Boolean
    default: true

steps:
  - description: 'Install Rook operator'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'rook'
      app: 'rook-ceph'
      chart: 'rook-release/rook-ceph'
      namespace: 'rook-ceph'
      repo_url: 'https://charts.rook.io/release'
      version: '1.15.5'
      wait: true
      deploy: $rook

  - description: 'Install Ceph cluster'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'ceph'
      app: 'rook-ceph-cluster'
      chart: 'rook-release/rook-ceph-cluster'
      namespace: 'rook-ceph'
      repo_url: 'https://charts.rook.io/release'
      version: '1.15.5'
      subcharts:
        - service: 'ceph-monitoring'
          app: 'kube-prometheus-stack'
          chart: 'prometheus-community/kube-prometheus-stack'
          repo_url: 'https://prometheus-community.github.io/helm-charts'
          version: '66.3.0'
      wait: true
      deploy: $ceph
