---
description: 'Configure storage'

parameters:
  nfs:
    description: 'Deploy NFS driver'
    type: Boolean
    default: true

  zfs:
    description: 'Deploy ZFS driver'
    type: Boolean
    default: true

steps:
  - description: 'Install NFS CSI driver'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'csi-driver-nfs'
      app: 'csi-driver-nfs'
      chart: 'csi-driver-nfs/csi-driver-nfs'
      namespace: 'kube-system'
      repo_url: 'https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts'
      version: '4.9.0'
      wait: true
      deploy: $nfs

  - description: 'Install LocalPV-ZFS CSI driver'
    plan: 'nest::kubernetes::deploy'
    parameters:
      service: 'zfs-localpv'
      app: 'zfs-localpv'
      chart: 'openebs-zfslocalpv/zfs-localpv'
      namespace: 'openebs'
      repo_url: 'https://openebs.github.io/zfs-localpv'
      version: '2.6.2'
      deploy: $zfs
