---
description: 'Deploy container registry'

parameters:
  resources:
    description: 'Deploy resources'
    type: Boolean
    default: false

  registry:
    description: 'Deploy registry'
    type: Boolean
    default: true

steps:
  - description: 'Deploy resources'
    plan: nest::kubernetes::deploy
    parameters:
      service: 'registry-resources'
      app: 'scratch'
      deploy: $resources
      wait: true

  - description: 'Deploy registry'
    plan: nest::kubernetes::deploy
    parameters:
      service: 'registry'
      chart: 'mya/registry'
      repo_url: 'https://mya.sh'
      version: '22.4.11'
      deploy: $registry
