---
description: 'Tear down a Kubernetes cluster'

parameters:
  name:
    type: String
    description: 'Name of the cluster'

  control_plane:
    type: TargetSpec
    description: 'Control plane to reset'

  vip:
    type: Stdlib::IP::Address::V4
    description: 'Address control plane is reachable on'

  nodes:
    type: TargetSpec
    default: []
    description: 'Nodes to reset'

steps:
  - description: 'Remove nodes'
    plan: nest::kubernetes::remove_node
    parameters:
      drain: false
    targets: $nodes

  - description: 'Reset control plane'
    command: 'kubeadm reset --force'
    run_as: root
    targets: $control_plane

  # Cleanup leftover from kube-vip
  - description: 'Remove VIP'
    command: "ip addr delete dev lo ${vip}/32"
    catch_errors: true
    run_as: root
    targets: $control_plane

  # Cleanup old kube-proxy IPVS rules
  - description: 'Clear IPVS'
    command: 'ipvsadm --clear'
    catch_errors: true
    run_as: root
    targets: "${control_plane} ${nodes}"

  - description: 'Remove Kubeconfig'
    command: "rm -f '/nest/home/kubeconfigs/${name}.conf'"
    targets: localhost
