---
description: 'Tear down a Kubernetes cluster'

parameters:
  name:
    type: String
    description: 'Name of the cluster'

  control_plane:
    type: TargetSpec
    description: 'Control plane to reset'

  vip:
    type: Stdlib::IP::Address::V4
    description: 'Address control plane is reachable on'

  workers:
    type: TargetSpec
    default: []
    description: 'Workers to reset'

steps:
  - description: 'Remove worker nodes'
    plan: nest::kubernetes::remove_worker
    parameters:
      drain: false
    targets: $workers

  - description: 'Reset control plane'
    command: 'kubeadm reset --force'
    run_as: root
    targets: $control_plane

  # Cleanup leftover from kube-vip
  - description: 'Remove VIP'
    command: "ip addr delete dev lo ${vip}/32"
    catch_errors: true
    run_as: root
    targets: $control_plane

  # Reset connections between control plane nodes...
  # They reconnect to each other after the kube-vip pods are destroyed
  - description: 'Restart BGP service'
    command: "systemctl restart bird"
    run_as: root
    targets: $control_plane

  - description: 'Remove Kubeconfig'
    command: "rm -f '/nest/home/kubeconfigs/${name}.conf'"
    targets: localhost
