---
description: 'Tear down a Kubernetes cluster'

parameters:
  control_plane:
    type: TargetSpec
    description: The control plane to reset

  workers:
    type: TargetSpec
    default: []
    description: A list of workers to reset

steps:
  - description: 'Remove worker nodes'
    plan: nest::kubernetes::remove_worker
    parameters:
      control_plane: $control_plane
    targets: $workers

  - description: 'Reset control plane'
    command: 'kubeadm reset --force'
    run_as: root
    targets: $control_plane

  - description: 'Delete CNI interfaces'
    plan: nest::kubernetes::delete_network
    targets: $control_plane
