---
description: 'Upgrade Kubernetes components'

steps:
  # - description: 'Upgrade Calico'
  #   plan: 'nest::kubernetes::deploy'
  #   parameters:
  #     service: 'calico'
  #     app: 'tigera-operator'
  #     namespace: 'tigera-operator'
  #     repo_name: 'projectcalico'
  #     repo_url: 'https://docs.tigera.io/calico/charts'
  #     version: '3.28.0'
  #     wait: true

  # - description: 'Upgrade MetalLB'
  #   plan: 'nest::kubernetes::deploy'
  #   parameters:
  #     service: 'metallb'
  #     app: 'metallb'
  #     namespace: 'metallb-system'
  #     repo_name: 'metallb'
  #     repo_url: 'https://metallb.github.io/metallb'
  #     version: '0.14.5'
  #     wait: true

  # - description: 'Upgrade NFS CSI driver'
  #   plan: 'nest::kubernetes::deploy'
  #   parameters:
  #     service: 'csi-driver-nfs'
  #     app: 'csi-driver-nfs'
  #     namespace: 'kube-system'
  #     repo_name: 'csi-driver-nfs'
  #     repo_url: 'https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts'
  #     version: '4.7.0'
  #     wait: true

  # - description: 'Upgrade Kubernetes Dashboard'
  #   plan: 'nest::kubernetes::deploy'
  #   parameters:
  #     service: 'kubernetes-dashboard'
  #     app: 'kubernetes-dashboard'
  #     namespace: 'kubernetes-dashboard'
  #     repo_name: 'kubernetes-dashboard'
  #     repo_url: 'https://kubernetes.github.io/dashboard/'
  #     version: '7.4.0'
  #     wait: true
