---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: eyrie
  namespace: metallb-system
spec:
  addresses:
  - 172.21.0.0/17
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: eyrie
  namespace: metallb-system
spec:
  ipAddressPools:
  - eyrie
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: falcon
  namespace: metallb-system
spec:
  myASN: 65000
  peerASN: 65000
  peerAddress: 172.22.4.2
  nodeSelectors:
  - matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values: [eaglet1, eaglet2, eaglet3, eaglet4, eaglet5, eaglet6]
