---
description: 'Build the eyrie Kubernetes cluster'

steps:
  - description: 'Pull Kubernetes images'
    plan: nest::kubernetes::pull_images
    targets: eyrie-control-plane

  - description: 'Initialize control plane'
    plan: nest::kubernetes::init
    parameters:
      name: eyrie
      control_plane_endpoint: control-plane.eyrie
      vip: 172.21.255.255
    targets: eyrie-control-plane

  - description: 'Setup container networking'
    plan: nest::kubernetes::setup
    parameters:
      control_plane: eyrie-control-plane

  - description: 'Join worker nodes'
    plan: nest::kubernetes::join_node
    parameters:
      control_plane: eyrie-control-plane
    targets: eyrie-workers

  - description: 'Join storage nodes'
    plan: nest::kubernetes::join_node
    parameters:
      control_plane: eyrie-control-plane
      taints: role=storage:NoSchedule
    targets: eyrie-storage

  - description: 'Join monitor nodes'
    plan: nest::kubernetes::join_node
    parameters:
      control_plane: eyrie-control-plane
      taints: role=monitor:NoSchedule
    targets: eyrie-monitor

  - description: 'Join workstation nodes'
    plan: nest::kubernetes::join_node
    parameters:
      control_plane: eyrie-control-plane
      taints: role=workstation:NoSchedule
    targets: eyrie-workstations

  - description: 'Rebalance CoreDNS'
    plan: nest::kubernetes::restart_deployment
    parameters:
      name: coredns
      namespace: kube-system

  - description: 'Configure network'
    plan: nest::kubernetes::configure_network

  - description: 'Configure storage'
    plan: nest::kubernetes::configure_storage

  - description: 'Configure ingress'
    plan: nest::kubernetes::configure_ingress

  - description: 'Configure Ceph'
    plan: nest::kubernetes::configure_ceph

  - description: 'Configure monitoring'
    plan: nest::kubernetes::configure_monitoring

  - description: 'Deploy Kubernetes Dashboard'
    plan: nest::kubernetes::deploy_dashboard
