---
description: 'Build the eyrie Kubernetes cluster'

steps:
  - description: 'Pull Kubernetes images'
    plan: nest::kubernetes::pull_images
    targets: eyrie-control-plane

  - description: 'Initialize control plane'
    plan: nest::kubernetes::init
    parameters:
      target: eyrie-control-plane
      name: eyrie

  - description: 'Join worker nodes'
    plan: nest::kubernetes::join_node
    parameters:
      control_plane: eyrie-control-plane
    targets: eyrie-workers

  - description: 'Rebalance CoreDNS'
    plan: nest::kubernetes::restart_deployment
    parameters:
      name: coredns
      namespace: kube-system
    targets: eyrie-control-plane
